### PR TITLE
Group comments

### PR DESCRIPTION
**Pull request by philleski**
Please put comments, questions, suggestions here.

### CODE REVIEW

**Comment by camsjams** [comment]
Does the scope of this style guide cover boolean variable and function names (they are kind of touched upon but not in detail)?

### positive boolean names
    // bad
    theData = true;
    // considerably bad, confusing
    hasNoData = false;
    
    // good
    var hasData = false;
    var isValid = !!someObj.val;

### abstracting boolean chains to well named functions
    // not easy to scan
    if (!myData && (myOtherData && myOtherData.option && myOtherData.option === 'specialParam' && myOtherData.fallback !== false)) {
        // do stuff here
    }
       
    // easier to scan
     if (!myData && hasOverride(myOtherData)) {
        // do stuff here
    }

### callbacks vs promises
Callbacks don't allow us to write as much functional code with discrete input and output, as a callback-based function has to be aware of it's caller and complete that contract. 

Can we mention promises as an optional alternative :+1:

**Comment by nimbus154** [comment]
@camsjams your suggestions are well within the scope of this document, which is intended to be both style guide and best practice reference.

Your Boolean naming and function extraction suggestions are definitely good practices and worth including.

I am also happy to include promises in the document as an alternative to callbacks. I wonder how we can best include them and what this document should prescribe. For instance, we could include a promises section, describe promise best practices, and present it as an alternative to callbacks.

The inclusion of promises implicitly begs broader, hairier questions: should we comment on integrating promises into an existing, callback-based application? Should we prescribe one control flow approach over the other? I'm concerned that the omission of these guidelines could lead to a codebase where the multiplicity of control flow patterns leads to uncertainty about how to use a function. That said, I don't want paranoia to hinder our adoption of promises. Since we've always been a callback shop, I am only speculating and should research best practices in this area.

I'm curious if others have thoughts on this.

**Comment by mpalmerlee** [comment]
I'm not sure what to do about saying when to use promises vs. callbacks, I think we can give implementer freedom in cases like this, give enough information to know the pros and cons of each approach and when to use which tool in which cases.

**Comment by mpalmerlee** [comment]
Personally I like using the .js extension when requiring local files in the project and not (obviously?) using them when including npm modules.  This helps me find uses of the file within the project, where in this case searching the project for "Car" may have far more occurrences, you could search for "models/Car" but that will not always work based on path and relative path.

Do not use the .js when requiring modules
```javascript
  // bad
  var Batmobil = require('./models/Car.js');

  // good
  var Batmobil = require('./models/Car');

**Comment by mpalmerlee** [comment]
They cover Naming Conventions (hurray!), I'm guessing variable name naming conventions should match object property naming conventions? I'm thinking of our config files and conversion between database properties to object properties, etc...

**Comment by cleathers** [comment]
About the requiring of local files. You could always just `grep -irn require.*car ./`
I'm a fan of leaving the .js off b/c I'm lazy.

**Comment by mpalmerlee** [comment]
@cleathers yes you could do that, but not having to use a regex I think is easier. My philosophy is that I'd rather be lazy when reading (searching) code then when writing code, since we tend to write it once (or relatively rarely) and then spend countless more time reading and understanding code

**Comment by cleathers** [comment]
That's a good point @mpalmerlee

**Comment by nimbus154** [comment]
I am closing this PR because it covers too many issues.

If you have a specific suggestion or objection to the guide, please open a PR with your desired edits. However, before you open a PR, check if there are existing, related PRs. Thanks!

**Pull request closed without merging**
