### PR TITLE
Updated README.md to encourage using .js extension

### PR DESCRIPTION
**Pull request by mpalmerlee**
For local files

### CODE REVIEW

**Comment by nimbus154** [comment]
I omit file extensions so that I can easily refactor single files into a directory with an index file. However, this use case happens much less frequently than finding references, and it makes sense to update `require` references when refactoring.

How do you feel about using `require('./car')` if `car` is a directory containing an `index.js`?

**Comment by mpalmerlee** [comment]
That's fine with me because it's a separate feature than requiring a single file.  I'll adjust to include a note about that.

**Comment by nimbus154** [comment]
Sounds good.

**Comment by mpalmerlee** [comment]
@nimbus154 I've added that section with a link to how node works with the folder as module method for requires

**Comment by nimbus154** [comment]
I'm cool with this. @philleski any objections?

**Pull request merged**
